In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [20]:
n_instr = 6
st = 4

In [21]:
step = np.array([2,3,4,6,8,10]) # same length as n_instr
step

array([ 2,  3,  4,  6,  8, 10])

In [22]:
n_neuron = 12

In [23]:
period = (n_neuron/step).astype(int)
period

array([6, 4, 3, 2, 1, 1])

In [32]:
p = {}
for i in range(n_instr):
    p[step[i]] = np.random.rand(period[i],1)
p

{2: array([[0.56446758],
        [0.457069  ],
        [0.49377983],
        [0.3842398 ],
        [0.56403352],
        [0.51888178]]),
 3: array([[0.27463944],
        [0.68424481],
        [0.90349501],
        [0.04255045]]),
 4: array([[0.67890196],
        [0.69249261],
        [0.86750381]]),
 6: array([[0.81450892],
        [0.36538072]]),
 8: array([[0.63499174]]),
 10: array([[0.69943108]])}

In [54]:
n_data = 800
keys_p = [*p]
dataset = np.zeros((n_neuron,n_data))
for i in range(n_instr):
    q = p[keys_p[i]]
    sample = (q > np.random.rand(len(q),n_data)).astype(int)
    start = np.random.randint(st,size=n_data)
    
    step = keys_p[i]
    for j in range(n_data):
        x = np.arange(start[j],n_neuron,step)
        dataset[x,j] += sample[:x.size,j]

In [61]:
dataset = (dataset>0).astype(int)

In [63]:
dataset.sum(axis=1)/n_data

array([0.65375, 0.64875, 0.68625, 0.75375, 0.48375, 0.48375, 0.64875,
       0.54   , 0.6375 , 0.65875, 0.59125, 0.63875])

### New Attempt

In [3]:
step = np.array([2,3,4]) # same length as n_instr
step

array([2, 3, 4])

In [4]:
n_neuron = 12
period = (n_neuron/step).astype(int)
period

array([6, 4, 3])

In [154]:
n_data = 500

In [155]:
d = np.zeros((n_neuron,n_data),dtype=int)
for i in range(step.size):
    d[np.arange(0,n_neuron,step[i]),:] += (np.random.rand(period[i],n_data)>0.5).astype(int)
dataset1 = (d>0).astype(int)

In [156]:
dataset1.sum(axis=1)/n_data

array([0.88 , 0.   , 0.462, 0.48 , 0.768, 0.   , 0.73 , 0.   , 0.71 ,
       0.448, 0.514, 0.   ])

In [157]:
d = np.zeros((n_neuron,n_data),dtype=int)
d[np.arange(1,n_neuron,step[0]),:] += (np.random.rand(period[0],n_data)>0.5).astype(int)
for i in range(1,step.size):
    d[np.arange(0,n_neuron,step[i]),:] += (np.random.rand(period[i],n_data)>0.5).astype(int)
dataset2 = (d>0).astype(int)

In [158]:
dataset2.sum(axis=1)/n_data

array([0.742, 0.488, 0.   , 0.776, 0.52 , 0.488, 0.544, 0.522, 0.532,
       0.726, 0.   , 0.508])

In [159]:
dataset = np.append(dataset1,dataset2,axis=1)
dataset.shape

(12, 1000)

In [160]:
dataset.sum(axis=1)/(n_data*2)

array([0.811, 0.244, 0.231, 0.628, 0.644, 0.244, 0.637, 0.261, 0.621,
       0.587, 0.257, 0.254])